import { money, fmtRange, catById } from '../../lib.js'
import { PageHeader, Card, SectionTitle, Stat, Btn, Icon } from '../ui.jsx'

const CHECKLIST = [
  { key: 'pay', label: 'Settle vendor payments' },
  { key: 'invoices', label: 'Issue & file invoices' },
  { key: 'survey', label: 'Send feedback survey to guests' },
  { key: 'archive', label: 'Close & archive the event' },
]

export default function Closing({ retreat, vendors, closing, onToggle }) {
  const spent = vendors.reduce((s, v) => s + (Number(v.price) || 0), 0)
  const margin = (Number(retreat.budget) || 0) - spent
  const outstanding = vendors.filter((v) => v.status !== 'done').reduce((s, v) => s + (Number(v.price) || 0), 0)
  const doneCount = CHECKLIST.filter((c) => closing[c.key]).length

  const exportReport = () => {
    const lines = [
      `# ${retreat.name || 'Retreat'} — Summary`,
      ``,
      `Dates: ${fmtRange(retreat.startDate, retreat.endDate)}`,
      `Location: ${retreat.location || '—'}`,
      `Concept: ${retreat.concept || '—'}`,
      `Participants: ${(retreat.participants || []).length}${retreat.target ? ` / ${retreat.target}` : ''}`,
      ``,
      `## Financials`,
      `Budget: ${money(retreat.budget)}`,
      `Vendor spend: ${money(spent)}`,
      `Gross margin: ${money(margin)}`,
      ``,
      `## Vendors`,
      ...vendors.map((v) => `- ${v.name} (${catById(v.category).label}) — ${money(v.price)} · ${v.status}`),
      ``,
      `Generated by Retreat OS`,
    ]
    const blob = new Blob([lines.join('\n')], { type: 'text/markdown;charset=utf-8' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `${(retreat.name || 'retreat').replace(/\s+/g, '-').toLowerCase()}-summary.md`
    a.click()
    URL.revokeObjectURL(a.href)
  }

  return (
    <div>
      <PageHeader icon="CheckCircle2" title="Wrap-up"
        subtitle="Settle the books, finish the closing checklist, and export the summary." />

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-5">
        <Stat icon="Wallet" label="Final spend" value={money(spent)} sub={`Budget ${money(retreat.budget)}`} />
        <Stat icon="ChartNoAxesColumn" label="Gross margin" value={money(margin)} tone={margin >= 0 ? 'emerald' : 'rose'} />
        <Stat icon="Receipt" label="Outstanding" value={money(outstanding)} sub="to vendors" tone={outstanding ? 'amber' : 'stone'} />
        <Stat icon="CheckCircle2" label="Checklist" value={`${doneCount}/${CHECKLIST.length}`} tone={doneCount === CHECKLIST.length ? 'emerald' : 'amber'} progress={Math.round(doneCount / CHECKLIST.length * 100)} />
      </div>

      <div className="grid lg:grid-cols-2 gap-4">
        <Card className="fade-up" pad={false}>
          <div className="px-5 pt-4 pb-2"><SectionTitle icon="CheckCircle2">Closing checklist</SectionTitle></div>
          <div className="divide-y divide-stone-100">
            {CHECKLIST.map((c) => (
              <button key={c.key} onClick={() => onToggle(c.key)} className="w-full flex items-center gap-3 px-5 py-3 text-left hover:bg-stone-50/60 transition">
                <span className={`size-5 shrink-0 rounded-md grid place-items-center ring-1 ${closing[c.key] ? 'bg-emerald-600 text-white ring-emerald-600' : 'bg-white ring-stone-300'}`}>{closing[c.key] && <Icon name="Check" size="xs" strokeWidth={3} className="pop-check" />}</span>
                <span className={`flex-1 text-sm ${closing[c.key] ? 'line-through text-stone-400' : 'text-stone-700 font-medium'}`}>{c.label}</span>
              </button>
            ))}
          </div>
        </Card>

        <Card className="fade-up">
          <SectionTitle icon="Download">Summary report</SectionTitle>
          <p className="text-sm text-stone-500 mb-4">Export a one-file recap — dates, financials and the full vendor list — to share or archive.</p>
          <div className="rounded-lg bg-stone-50 ring-1 ring-stone-200 p-4 text-sm text-stone-600 space-y-1">
            <div className="flex justify-between"><span>Budget</span><span className="font-semibold text-stone-700">{money(retreat.budget)}</span></div>
            <div className="flex justify-between"><span>Vendor spend</span><span className="font-semibold text-stone-700">{money(spent)}</span></div>
            <div className="flex justify-between"><span>Gross margin</span><span className={`font-semibold ${margin >= 0 ? 'text-emerald-700' : 'text-rose-600'}`}>{money(margin)}</span></div>
          </div>
          <Btn icon="Download" className="w-full mt-4" onClick={exportReport}>Export summary report</Btn>
        </Card>
      </div>
    </div>
  )
}
